/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exame;

import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class Motor extends javax.swing.JFrame {

    /**
     * Creates new form Motor
     */
    public Motor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        enunciado1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        titulo2 = new javax.swing.JLabel();
        Texto2 = new javax.swing.JTextField();
        titulo3 = new javax.swing.JLabel();
        texto3 = new javax.swing.JTextField();
        Mostrarinformacion = new javax.swing.JButton();
        Mostrardatos = new javax.swing.JButton();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("MOTOR");

        enunciado1.setText("Ingrese la marca del vehiculo:");

        texto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto1ActionPerformed(evt);
            }
        });

        titulo2.setText("Ingrese año de fabricacion del vehiculo:");

        titulo3.setText("El vehiculo presenta descomposiciones extra?");

        Mostrarinformacion.setText("Mostrar informacion");
        Mostrarinformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarinformacionActionPerformed(evt);
            }
        });

        Mostrardatos.setText("Mostrar datos");
        Mostrardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrardatosActionPerformed(evt);
            }
        });

        guardar.setText("Guardar datos");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(texto3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(titulo))
                                    .addComponent(enunciado1)
                                    .addComponent(titulo2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(texto1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Mostrarinformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mostrardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo)
                .addGap(26, 26, 26)
                .addComponent(enunciado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(titulo3)
                .addGap(26, 26, 26)
                .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mostrarinformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mostrardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarinformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarinformacionActionPerformed
        // Generar un número aleatorio entre 1 y 3 para determinar el estado del motor
        int estadoAleatorio = (int) (Math.random() * 3) + 1;

        // Definir el mensaje según el estado aleatorio generado
        String mensaje;
        switch (estadoAleatorio) {
            case 1:
                mensaje = "El motor está en buen estado.";
                break;
            case 2:
                mensaje = "El motor presenta filtraciones.";
                break;
            case 3:
                mensaje = "El motor es irreparable.";
                break;
            default:
                mensaje = "No se pudo determinar el estado del motor.";
                break;
        }

        // Mostrar el mensaje emergente con la información sobre el estado del motor
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_MostrarinformacionActionPerformed

    private void texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto1ActionPerformed

    private void MostrardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrardatosActionPerformed
        String marcaCarro = texto1.getText();
        String añoFabricacion = Texto2.getText();
        String otrosErrores = texto3.getText();

        // Mostrar cada texto en una ventana emergente consecutiva
        JOptionPane.showMessageDialog(this, "Marca de carro: " + marcaCarro);
        JOptionPane.showMessageDialog(this, "Año de fabricación: " + añoFabricacion);
        JOptionPane.showMessageDialog(this, "Otros errores: " + otrosErrores);
    }//GEN-LAST:event_MostrardatosActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
    
        String[] datos = new String[3];
        
        String marcaCarro = texto1.getText();
        String añoFabricacion = Texto2.getText();
        String otrosErrores = texto3.getText();

        // Guardar los datos en el arreglo
        datos[0] = marcaCarro;
        datos[1] = añoFabricacion;
        datos[2] = otrosErrores;

        // Mostrar un mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Los datos han sido guardados correctamente.");
    
    }//GEN-LAST:event_guardarActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Motor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Motor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Motor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Motor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Motor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrardatos;
    private javax.swing.JButton Mostrarinformacion;
    private javax.swing.JTextField Texto2;
    private javax.swing.JLabel enunciado1;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto3;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables
}
