package Leccion_poo;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;
import com.mongodb.MongoException;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import org.bson.Document;

public class Running extends javax.swing.JFrame {
    private MongoDatabase database = null;
    private MongoCollection<Document> collection = null;
    DB db;
    DBCollection DatosRunning;
    BasicDBObject backup;

    public Running() {
        MongoClient mongo = null;
        String servidor = "localhost";
        Integer puerto = 27017;
        
        try {
            mongo = new MongoClient(servidor,puerto);
            db = mongo.getDB("TiemposDeCarrera");
            DatosRunning = db.getCollection("DatosRunning");
            
            
            System.out.println("Se conecto correctamente a MongoDB");
        } catch (MongoException e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            
        }

        initComponents();
 
    }

    // Elimina este método, ya que es generado automáticamente por NetBeans
    // private void initComponents() { }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Tcarrera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tcarrera2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tcarrera3 = new javax.swing.JTextField();
        Btnguardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Running-Marca");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese su Tiempo de carrera");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        Tcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcarreraActionPerformed(evt);
            }
        });
        getContentPane().add(Tcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, -1));

        jLabel4.setFont(new java.awt.Font("Cascadia Code", 2, 10)); // NOI18N
        jLabel4.setText("(hh:mm:ss)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 70, 20));

        jLabel2.setFont(new java.awt.Font("Cascadia Code", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese su distancia recorrida");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(Tcarrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 317, -1));

        jLabel3.setFont(new java.awt.Font("Cascadia Code", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese su frecuencia cardiaca (opcional)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(Tcarrera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 317, -1));

        Btnguardar.setBackground(new java.awt.Color(102, 255, 153));
        Btnguardar.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        Btnguardar.setText("Guardar");
        Btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(Btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(51, 102, 255));
        jButtonSalir.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.setToolTipText("");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcarreraActionPerformed

    private void BtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnguardarActionPerformed
       BasicDBObject document = new BasicDBObject();
        document.put("Tiempo de carrera","'"+Tcarrera.getText()+"'" );
        document.put("Distancia de carrera ","'"+Tcarrera2.getText()+"'" );
        document.put("Frecuencia cardiaca",Tcarrera3.getText() );
        DatosRunning.insert(document);
    }//GEN-LAST:event_BtnguardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Running.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Running.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Running.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Running.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Running().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnguardar;
    private javax.swing.JTextField Tcarrera;
    private javax.swing.JTextField Tcarrera2;
    private javax.swing.JTextField Tcarrera3;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}